#############################################################################
# Makefile for building: Synkron
# Generated by qmake (2.01a) (Qt 4.4.0) on: ?????? 29. ???? 14:30:41 2008
# Project:  Synkron.pro
# Template: app
# Command: z:\eclipse\qt\bin\qmake -win32 -o Makefile Synkron.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = z:\eclipse\qt\bin\qmake
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Synkron.pro  z:/eclipse/qt/mkspecs/win32-g++/qmake.conf z:/eclipse/qt/mkspecs/qconfig.pri \
		z:/eclipse/qt/mkspecs/features/qt_functions.prf \
		z:/eclipse/qt/mkspecs/features/qt_config.prf \
		z:/eclipse/qt/mkspecs/features/exclusive_builds.prf \
		z:/eclipse/qt/mkspecs/features/default_pre.prf \
		z:/eclipse/qt/mkspecs/features/win32/default_pre.prf \
		z:/eclipse/qt/mkspecs/features/release.prf \
		z:/eclipse/qt/mkspecs/features/debug_and_release.prf \
		z:/eclipse/qt/mkspecs/features/default_post.prf \
		z:/eclipse/qt/mkspecs/features/win32/rtti.prf \
		z:/eclipse/qt/mkspecs/features/win32/exceptions.prf \
		z:/eclipse/qt/mkspecs/features/win32/stl.prf \
		z:/eclipse/qt/mkspecs/features/shared.prf \
		z:/eclipse/qt/mkspecs/features/warn_on.prf \
		z:/eclipse/qt/mkspecs/features/qt.prf \
		z:/eclipse/qt/mkspecs/features/win32/thread.prf \
		z:/eclipse/qt/mkspecs/features/moc.prf \
		z:/eclipse/qt/mkspecs/features/win32/windows.prf \
		z:/eclipse/qt/mkspecs/features/resources.prf \
		z:/eclipse/qt/mkspecs/features/uic.prf \
		z:/eclipse/qt/mkspecs/features/yacc.prf \
		z:/eclipse/qt/mkspecs/features/lex.prf \
		z:/eclipse/qt/lib/qtmain.prl
	$(QMAKE) -win32 -o Makefile Synkron.pro
z:\eclipse\qt\mkspecs\qconfig.pri:
z:\eclipse\qt\mkspecs\features\qt_functions.prf:
z:\eclipse\qt\mkspecs\features\qt_config.prf:
z:\eclipse\qt\mkspecs\features\exclusive_builds.prf:
z:\eclipse\qt\mkspecs\features\default_pre.prf:
z:\eclipse\qt\mkspecs\features\win32\default_pre.prf:
z:\eclipse\qt\mkspecs\features\release.prf:
z:\eclipse\qt\mkspecs\features\debug_and_release.prf:
z:\eclipse\qt\mkspecs\features\default_post.prf:
z:\eclipse\qt\mkspecs\features\win32\rtti.prf:
z:\eclipse\qt\mkspecs\features\win32\exceptions.prf:
z:\eclipse\qt\mkspecs\features\win32\stl.prf:
z:\eclipse\qt\mkspecs\features\shared.prf:
z:\eclipse\qt\mkspecs\features\warn_on.prf:
z:\eclipse\qt\mkspecs\features\qt.prf:
z:\eclipse\qt\mkspecs\features\win32\thread.prf:
z:\eclipse\qt\mkspecs\features\moc.prf:
z:\eclipse\qt\mkspecs\features\win32\windows.prf:
z:\eclipse\qt\mkspecs\features\resources.prf:
z:\eclipse\qt\mkspecs\features\uic.prf:
z:\eclipse\qt\mkspecs\features\yacc.prf:
z:\eclipse\qt\mkspecs\features\lex.prf:
z:\eclipse\qt\lib\qtmain.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -win32 -o Makefile Synkron.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
