#############################################################################
# Makefile for building: synkron
# Generated by qmake (2.01a) (Qt 4.5.1) on: Wed Jun 24 04:08:10 2009
# Project:  Synkron.pro
# Template: app
# Command: /home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/qmake -spec /home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/linux-g++ -unix -o Makefile Synkron.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUSE_UNIX_TOUCH_COMMAND -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/linux-g++ -I. -I/home/mbnoimi/Apps/qtsdk-2009.02/qt/include/QtCore -I/home/mbnoimi/Apps/qtsdk-2009.02/qt/include/QtNetwork -I/home/mbnoimi/Apps/qtsdk-2009.02/qt/include/QtGui -I/home/mbnoimi/Apps/qtsdk-2009.02/qt/include/QtXml -I/home/mbnoimi/Apps/qtsdk-2009.02/qt/include -I.tmp.unix -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib
LIBS          = $(SUBLIBS)  -L/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib -lQtXml -L/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib -pthread -pthread -lQtGui -L/usr/X11R6/lib -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtNetwork -pthread -pthread -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .tmp.unix/

####### Files

SOURCES       = main.cpp \
		sync.cpp \
		restore.cpp \
		blacklist.cpp \
		multisync.cpp \
		scheduler.cpp \
		filters.cpp \
		mtfile.cpp \
		syncfolders.cpp \
		syncview.cpp \
		analyse.cpp \
		tabs.cpp \
		other.cpp \
		settings.cpp \
		syncdb.cpp .tmp.unix/moc_main_window.cpp \
		.tmp.unix/moc_syncpage.cpp \
		.tmp.unix/moc_mtfile.cpp \
		.tmp.unix/moc_mtadvancedgroupbox.cpp \
		.tmp.unix/moc_extendedlineedit.cpp \
		.tmp.unix/moc_extendedlistwidget.cpp \
		.tmp.unix/moc_extendedtreewidget.cpp \
		.tmp.unix/moc_syncfolders.cpp \
		.tmp.unix/moc_mtpathdialogue.cpp \
		.tmp.unix/qrc_resources.cpp \
		.tmp.unix/qrc_i18n.cpp
OBJECTS       = .tmp.unix/main.o \
		.tmp.unix/sync.o \
		.tmp.unix/restore.o \
		.tmp.unix/blacklist.o \
		.tmp.unix/multisync.o \
		.tmp.unix/scheduler.o \
		.tmp.unix/filters.o \
		.tmp.unix/mtfile.o \
		.tmp.unix/syncfolders.o \
		.tmp.unix/syncview.o \
		.tmp.unix/analyse.o \
		.tmp.unix/tabs.o \
		.tmp.unix/other.o \
		.tmp.unix/settings.o \
		.tmp.unix/syncdb.o \
		.tmp.unix/moc_main_window.o \
		.tmp.unix/moc_syncpage.o \
		.tmp.unix/moc_mtfile.o \
		.tmp.unix/moc_mtadvancedgroupbox.o \
		.tmp.unix/moc_extendedlineedit.o \
		.tmp.unix/moc_extendedlistwidget.o \
		.tmp.unix/moc_extendedtreewidget.o \
		.tmp.unix/moc_syncfolders.o \
		.tmp.unix/moc_mtpathdialogue.o \
		.tmp.unix/qrc_resources.o \
		.tmp.unix/qrc_i18n.o
DIST          = /home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/release.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf \
		Synkron.pro
QMAKE_TARGET  = synkron
DESTDIR       = 
TARGET        = synkron

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_main_window.h ui_about.h ui_multisync_page.h ui_sync_view_item.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Synkron.pro  /home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/linux-g++/qmake.conf /home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/release.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib/libQtXml.prl \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib/libQtCore.prl \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib/libQtGui.prl \
		/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec /home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/linux-g++ -unix -o Makefile Synkron.pro
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/common/g++.conf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/common/unix.conf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/common/linux.conf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/qconfig.pri:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/release.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/default_post.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/qt.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/moc.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/resources.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/uic.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/yacc.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/lex.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib/libQtXml.prl:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib/libQtCore.prl:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib/libQtGui.prl:
/home/mbnoimi/Apps/qtsdk-2009.02/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /home/mbnoimi/Apps/qtsdk-2009.02/qt/mkspecs/linux-g++ -unix -o Makefile Synkron.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp.unix/synkron1.0.0 || $(MKDIR) .tmp.unix/synkron1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp.unix/synkron1.0.0/ && $(COPY_FILE) --parents main_window.h syncpage.h mtfile.h mtadvancedgroupbox.h extendedlineedit.h extendedlistwidget.h extendedtreewidget.h syncfolders.h mtstringset.h mtpathdialogue.h mtdictionary.h .tmp.unix/synkron1.0.0/ && $(COPY_FILE) --parents resources.qrc i18n.qrc .tmp.unix/synkron1.0.0/ && $(COPY_FILE) --parents main.cpp sync.cpp restore.cpp blacklist.cpp multisync.cpp scheduler.cpp filters.cpp mtfile.cpp syncfolders.cpp syncview.cpp analyse.cpp tabs.cpp other.cpp settings.cpp syncdb.cpp .tmp.unix/synkron1.0.0/ && $(COPY_FILE) --parents main_window.ui about.ui multisync_page.ui sync_view_item.ui .tmp.unix/synkron1.0.0/ && $(COPY_FILE) --parents i18n/Synkron-Slovak.ts i18n/Synkron-German.ts i18n/Synkron-Japanese.ts i18n/Synkron-Arabic.ts i18n/Synkron-Russian.ts i18n/Synkron-Spanish.ts i18n/Synkron-Brazilian_Portuguese.ts i18n/Synkron-Polish.ts i18n/Synkron-Italian.ts i18n/Synkron-French.ts i18n/Synkron-Valencian.ts i18n/Synkron-Finnish.ts .tmp.unix/synkron1.0.0/ && (cd `dirname .tmp.unix/synkron1.0.0` && $(TAR) synkron1.0.0.tar synkron1.0.0 && $(COMPRESS) synkron1.0.0.tar) && $(MOVE) `dirname .tmp.unix/synkron1.0.0`/synkron1.0.0.tar.gz . && $(DEL_FILE) -r .tmp.unix/synkron1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .tmp.unix/moc_main_window.cpp .tmp.unix/moc_syncpage.cpp .tmp.unix/moc_mtfile.cpp .tmp.unix/moc_mtadvancedgroupbox.cpp .tmp.unix/moc_extendedlineedit.cpp .tmp.unix/moc_extendedlistwidget.cpp .tmp.unix/moc_extendedtreewidget.cpp .tmp.unix/moc_syncfolders.cpp .tmp.unix/moc_mtpathdialogue.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .tmp.unix/moc_main_window.cpp .tmp.unix/moc_syncpage.cpp .tmp.unix/moc_mtfile.cpp .tmp.unix/moc_mtadvancedgroupbox.cpp .tmp.unix/moc_extendedlineedit.cpp .tmp.unix/moc_extendedlistwidget.cpp .tmp.unix/moc_extendedtreewidget.cpp .tmp.unix/moc_syncfolders.cpp .tmp.unix/moc_mtpathdialogue.cpp
.tmp.unix/moc_main_window.cpp: ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h \
		main_window.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) main_window.h -o .tmp.unix/moc_main_window.cpp

.tmp.unix/moc_syncpage.cpp: ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h \
		syncpage.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) syncpage.h -o .tmp.unix/moc_syncpage.cpp

.tmp.unix/moc_mtfile.cpp: mtfile.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) mtfile.h -o .tmp.unix/moc_mtfile.cpp

.tmp.unix/moc_mtadvancedgroupbox.cpp: mtadvancedgroupbox.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) mtadvancedgroupbox.h -o .tmp.unix/moc_mtadvancedgroupbox.cpp

.tmp.unix/moc_extendedlineedit.cpp: extendedlineedit.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) extendedlineedit.h -o .tmp.unix/moc_extendedlineedit.cpp

.tmp.unix/moc_extendedlistwidget.cpp: extendedlistwidget.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) extendedlistwidget.h -o .tmp.unix/moc_extendedlistwidget.cpp

.tmp.unix/moc_extendedtreewidget.cpp: extendedtreewidget.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) extendedtreewidget.h -o .tmp.unix/moc_extendedtreewidget.cpp

.tmp.unix/moc_syncfolders.cpp: syncfolders.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) syncfolders.h -o .tmp.unix/moc_syncfolders.cpp

.tmp.unix/moc_mtpathdialogue.cpp: mtpathdialogue.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) mtpathdialogue.h -o .tmp.unix/moc_mtpathdialogue.cpp

compiler_rcc_make_all: .tmp.unix/qrc_resources.cpp .tmp.unix/qrc_i18n.cpp
compiler_rcc_clean:
	-$(DEL_FILE) .tmp.unix/qrc_resources.cpp .tmp.unix/qrc_i18n.cpp
.tmp.unix/qrc_resources.cpp: resources.qrc \
		images/folder_red.png \
		images/folder.png \
		images/open.png \
		images/Synchronise.png \
		images/syncview_48.png \
		images/Synkron128_closetab.png \
		images/sync_all.png \
		images/sync.png \
		images/Synkron-about.png \
		images/configure16.png \
		images/clean_temp_16.png \
		images/save.png \
		images/file.png \
		images/file_red.png \
		images/tab-remove_32.png \
		images/scheduler16.png \
		images/filter16.png \
		images/Synkron48.png \
		images/ok_16.png \
		images/remove.png \
		images/reload.png \
		images/tab-new_32.png \
		images/multisync.png \
		images/Synkron16.png \
		images/Synkron128.png \
		images/folder_16.png \
		images/scheduler64.png \
		images/sync_schedule.png \
		images/stop_sync22.png \
		images/Restore.png \
		images/multisync_16.png \
		images/Restore16.png \
		images/folder_16_red.png \
		images/locale.png \
		images/analyse_16.png \
		images/clear_rtl.png \
		images/save-as.png \
		images/clear.png \
		images/sync22.png \
		images/add.png \
		images/blacklist.png \
		images/quit.png \
		images/filter32.png \
		images/sources.png \
		images/back.png
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/rcc -name resources resources.qrc -o .tmp.unix/qrc_resources.cpp

.tmp.unix/qrc_i18n.cpp: i18n.qrc \
		i18n/Synkron-Japanese.qm \
		i18n/Synkron-Slovak.qm \
		i18n/Synkron-i18n.qm \
		i18n/Synkron-Arabic.qm \
		i18n/Synkron-German.qm \
		i18n/Synkron-French.qm \
		i18n/Synkron-Finnish.qm \
		i18n/Synkron-Valencian.qm \
		i18n/Synkron-Polish.qm \
		i18n/Synkron-Italian.qm \
		i18n/Synkron-Spanish.qm \
		i18n/Synkron-Brazilian_Portuguese.qm \
		i18n/Synkron-Russian.qm
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/rcc -name i18n i18n.qrc -o .tmp.unix/qrc_i18n.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_main_window.h ui_about.h ui_multisync_page.h ui_sync_view_item.h
compiler_uic_clean:
	-$(DEL_FILE) ui_main_window.h ui_about.h ui_multisync_page.h ui_sync_view_item.h
ui_main_window.h: main_window.ui \
		extendedlineedit.h \
		mtadvancedgroupbox.h \
		extendedlistwidget.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/uic main_window.ui -o ui_main_window.h

ui_about.h: about.ui
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/uic about.ui -o ui_about.h

ui_multisync_page.h: multisync_page.ui \
		extendedlineedit.h \
		extendedtreewidget.h
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/uic multisync_page.ui -o ui_multisync_page.h

ui_sync_view_item.h: sync_view_item.ui
	/home/mbnoimi/Apps/qtsdk-2009.02/qt/bin/uic sync_view_item.ui -o ui_sync_view_item.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

.tmp.unix/main.o: main.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/main.o main.cpp

.tmp.unix/sync.o: sync.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/sync.o sync.cpp

.tmp.unix/restore.o: restore.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/restore.o restore.cpp

.tmp.unix/blacklist.o: blacklist.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/blacklist.o blacklist.cpp

.tmp.unix/multisync.o: multisync.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/multisync.o multisync.cpp

.tmp.unix/scheduler.o: scheduler.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/scheduler.o scheduler.cpp

.tmp.unix/filters.o: filters.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/filters.o filters.cpp

.tmp.unix/mtfile.o: mtfile.cpp mtfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/mtfile.o mtfile.cpp

.tmp.unix/syncfolders.o: syncfolders.cpp syncfolders.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/syncfolders.o syncfolders.cpp

.tmp.unix/syncview.o: syncview.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/syncview.o syncview.cpp

.tmp.unix/analyse.o: analyse.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/analyse.o analyse.cpp

.tmp.unix/tabs.o: tabs.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/tabs.o tabs.cpp

.tmp.unix/other.o: other.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/other.o other.cpp

.tmp.unix/settings.o: settings.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/settings.o settings.cpp

.tmp.unix/syncdb.o: syncdb.cpp main_window.h \
		ui_about.h \
		ui_sync_view_item.h \
		syncpage.h \
		ui_main_window.h \
		ui_multisync_page.h \
		mtfile.h \
		mtadvancedgroupbox.h \
		mtstringset.h \
		syncfolders.h \
		extendedtreewidget.h \
		mtpathdialogue.h \
		mtdictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/syncdb.o syncdb.cpp

.tmp.unix/moc_main_window.o: .tmp.unix/moc_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/moc_main_window.o .tmp.unix/moc_main_window.cpp

.tmp.unix/moc_syncpage.o: .tmp.unix/moc_syncpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/moc_syncpage.o .tmp.unix/moc_syncpage.cpp

.tmp.unix/moc_mtfile.o: .tmp.unix/moc_mtfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/moc_mtfile.o .tmp.unix/moc_mtfile.cpp

.tmp.unix/moc_mtadvancedgroupbox.o: .tmp.unix/moc_mtadvancedgroupbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/moc_mtadvancedgroupbox.o .tmp.unix/moc_mtadvancedgroupbox.cpp

.tmp.unix/moc_extendedlineedit.o: .tmp.unix/moc_extendedlineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/moc_extendedlineedit.o .tmp.unix/moc_extendedlineedit.cpp

.tmp.unix/moc_extendedlistwidget.o: .tmp.unix/moc_extendedlistwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/moc_extendedlistwidget.o .tmp.unix/moc_extendedlistwidget.cpp

.tmp.unix/moc_extendedtreewidget.o: .tmp.unix/moc_extendedtreewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/moc_extendedtreewidget.o .tmp.unix/moc_extendedtreewidget.cpp

.tmp.unix/moc_syncfolders.o: .tmp.unix/moc_syncfolders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/moc_syncfolders.o .tmp.unix/moc_syncfolders.cpp

.tmp.unix/moc_mtpathdialogue.o: .tmp.unix/moc_mtpathdialogue.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/moc_mtpathdialogue.o .tmp.unix/moc_mtpathdialogue.cpp

.tmp.unix/qrc_resources.o: .tmp.unix/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/qrc_resources.o .tmp.unix/qrc_resources.cpp

.tmp.unix/qrc_i18n.o: .tmp.unix/qrc_i18n.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp.unix/qrc_i18n.o .tmp.unix/qrc_i18n.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

